name: Second Workflow
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Run the server
          run: npm run dev < /dev/null & npx wait-on "http://localhost:5173" --timeout 10s
        - name: Cypress Tests
          run: npx cypress run