name: Third Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
        bom: ${{ steps.publish-bom.outputs.bom_list }}
    steps:
    - name: Detail content
      id: publish-bom
      run: |
        echo 'bom_list<<EOF' >> $GITHUB_OUTPUT
        find dist -name '*.js' -exec echo '{}' \; >> $GITHUB_OUTPUT 
        echo EOF >> $GITHUB_OUTPUT                               
# afficher liste fichier js
        

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Display BOM
      run: echo "${{ needs.build.outputs.bom }}"


